### ISSUE TITLE
Output file:line_no  of offending line when missing backquotes 

### ISSUE THREAD

**Issue by eksperimental** [pragdave/earmark#66]
I'm getting
> Closing unclosed backquotes ` at end of input

and I have no idea where to look at.
If it would mention the file name,  at least I would know where to look at.

**Comment by RobertDober** [comment]
@eksperimental some context might come in handy. Running `mix hex.docs` I might guess, but on which project?

**Comment by RobertDober** [comment]
@pragdave can you please wait with the release of 0.2.2 for this fix. I guess ex_doc might want to take advantage of the possibility to pass the filename into `.to_html`

**Comment by eksperimental** [comment]
It was run against the elixir project. So no mix env

**Comment by RobertDober** [comment]
oh I understand, it is in the nature of the bug that no context can be given ;(.

**Comment by eksperimental** [comment]
I google this issue, and I found that in the #elixir-lang irc channerl @KronicDeth shared that  he has been bitten by it as well.. I wonder if he was also not passing any context..

**Comment by RobertDober** [comment]
Sorry @eksperimental if I was not clear. You cannot pass the filename to Earmark right now and the line number is not added either to the warning message. I was talking of the context of the bug report, completely unrelated.
To be clear, the fix will:
* allow to call `Earmark.to_html(md_string, %Earmark.Options{filename: "hello.md"}`
* will add the filename and the line number to error messages.
* Then I (or any willing soul) will need to make a PR for ex_doc to add that information when invoking `Earmark.to_html`(hopefully easy).
As soon as that is done your problem should be solved, is that correct?

**Comment by RobertDober** [comment]
The above fix will have you count lines in your elixir sources. I was thinking that we could also allow a line number mapping to be passed into `.to_html` which could translate the line number from the markdown input to the line number in the original elixir file. I would be very interested in any POVs on this idea.

**Comment by eksperimental** [comment]
thanks for the fix Robert, but it is still not working in Elixir, I will open a new issue, because maybe it's only related to Elixir.

**Comment by RobertDober** [comment]
@eksperimental surprising it has been extensively tested. You might also want to test with the `deprecate-multiline-code` branch which is an idea we have been having. I do not know if Dave will eventually go into this direction as it is quite non-standard. Your feedback is appreciated.

**Comment by eksperimental** [comment]
that doesn't work either :-(
I get a whole bunch of errors like this,

> <no file>:1: warning: close pending "`", multiline inline code blocks
are deprecated

Multiline code blocks are quiet common in Elixir

oh.. one thing, there's a typo in your branch name
"deprecate-multline-code",
it's missing an "i"

thank you

**Comment by RobertDober** [comment]
@eksperimental  oh thanx I will fix that, however if multiline inline code is so common I guess we will not be able to ever deploy that branch ;(
